apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-workflow

spec:
  
  entrypoint: main

  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp3
      resources:
        requests:
          storage: 10Gi

  volumes:
  - name: container-build
    emptyDir: {}
  - name: kaniko-secret
    secret:
      secretName: dockercred
      items:
        - key: .dockerconfigjson
          path: config.json

  arguments:
    parameters:
    - name: repo_name
      value: "duplocloud-sample-web-app"
    - name: repo_owner
      value: "duplocloud"
    - name: git_branch
      value: "main"
    - name: container_tag
      value: "latest"
    - name: container_image
      value: "duplocloud-sample-web-app"
    - name: dockerfile
      value: "Dockerfile"

  templates:
    - name: main
      dag:
        tasks:
          - name: git-checkout
            templateRef:
              name: git-checkout
              template: main

          # build phase includes node build, docker image build, and docker push
          - name: container-build
            templateRef:
              name: container-build
              template: main
            depends: git-checkout

          - name: deploy
            templateRef:
              name: deploy
              template: main
            depends: container-build
