apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: container-build
  annotations:
    workflows.argoproj.io/description: >-
      Uses Kaniko to build a container image within Kubernetes.
    workflows.argoproj.io/maintainer: 'Pipekit Inc'
    workflows.argoproj.io/maintainer_url: 'https://github.com/pipekit/argo-workflows-ci-example'
    workflows.argoproj.io/version: '>= 3.3.6'
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: container-build
          template: container-build

  - name: container-build
    container:
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command: 
        - sh
        - -c
        - |
          cd /workdir/{{workflow.parameters.repo_name}}
          VERSION=$(cat /workdir/VERSION)
          
          /kaniko/executor --dockerfile="/workdir/{{workflow.parameters.repo_name}}/{{workflow.parameters.dockerfile}}" --destination=aboutte/{{workflow.parameters.container_image}}:$VERSION --context="dir:///workdir/{{workflow.parameters.repo_name}}/" --cache=true --use-new-run=true --reproducible=true --push-retry=3
          
          echo "============================================="
          echo "============================================="
          echo "App build, docker image build, and docker image push complete."
          echo "============================================="
          echo "============================================="
      volumeMounts:
        - name: container-build
          mountPath: /container-build
        - name: workdir
          mountPath: /workdir
        - name: kaniko-secret
          mountPath: /kaniko/.docker
      resources:
        requests:
          memory: 1Gi
          cpu: 1
    #20 minutes
    activeDeadlineSeconds: 1200
