apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-checkout
  annotations:
    workflows.argoproj.io/description: >-
      Clones a git repository and then performs a git checkout of a branch defined
      in the workflow workflow.parameters. Then merges in a defined target branch.
    workflows.argoproj.io/maintainer: 'Andy Boutte'
    workflows.argoproj.io/maintainer_url: 'https://github.com/aboutte'
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: git-checkout
          template: git-checkout

  - name: git-checkout
    container:
      image: alpine:latest
      command:
        - sh
        - -c
        - |
          apk --update add git

          cd /workdir
          echo "Start Clone of source branch"
          git clone https://github.com/{{workflow.parameters.repo_owner}}/{{workflow.parameters.repo_name}}.git
          cd {{workflow.parameters.repo_name}}

          date '+%s' > /workdir/VERSION
          chmod 777 /workdir/VERSION

          git checkout {{workflow.parameters.git_branch}}

          echo "============================================="
          echo "============================================="
          echo "Git checkout complete."
          echo "============================================="
          echo "============================================="



      volumeMounts:
      - name: "workdir"
        mountPath: /workdir
      resources:
        requests:
          memory: 250Mi
          cpu: 4m
    #20 minutes
    activeDeadlineSeconds: 1200